### ISSUE TITLE
Extra files in node_modules

### ISSUE THREAD

**Issue by mayankrathi04** [loopbackio/strong-error-handler#196]
# Description

When installing this package an additional file named grafana-enterprise-9.2.4.darwin-amd64.tar.gz is seen under node_modules/strong-error-handler . But this file is not present in the source code
 
# Steps to reproduce

- Create a new npm project: `npm init`

- `npm i strong-error-handler`

# Expected result

No additional files should be seen in node_modules/strong-error-handler apart from files in source code

# Actual result

Additional tar file  grafana-enterprise-9.2.4.darwin-amd64.tar.gz is seen

# Additional information

linux x64 18.12.1

**Comment by dhmlau** [comment]
@mayankrathi04, thanks for reporting this. I've added my investigation in PR #198.

**Comment by mgabeler-lee-6rs** [comment]
I don't see any CI configs to do the actual publishing, so I'm guessing that step has been done by a human? Perhaps this is just a stray file in the working directory of whichever human that has been for the last few releases?

**Comment by dhmlau** [comment]
@mgabeler-lee-6rs, it's just published. Thanks!
