### ISSUE TITLE
Security Vulnerability in Strong-Globalize

### ISSUE THREAD

**Issue by blankstar85** [loopbackio/strong-error-handler#81]
# Description/Steps to reproduce

npm install strong-error-handler, then npm audit

shows vulnerability in lodash in dependancy strong-globalize

# Link to reproduction sandbox

N/A

# Expected result

no vulnerabilities

# Additional information

reported in strong-globalize https://github.com/strongloop/strong-globalize/issues/139

Should update dependancy once udpated.

**Comment by jannyHou** [comment]
@blankstar85 Thanks for catching it. I will take a look and update the dependency.

**Comment by blankstar85** [comment]
I'm still getting this, I deleted my node_modules file and did an npm install.
this is what i have in my package.json
    "strong-error-handler": "^3.2.0",
